name: gong_web
description: gong_web
version: 0.0.1


environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  browser: ^0.10.0
  built_redux: "^6.0.0"
  coverage: "^0.9.3"
  dart_to_js_script_rewriter: ^1.0.1
  firebase: ^3.0.0
  test: "^0.12.24+8"
transformers:
- angular
- dart_to_js_script_rewriter
